baseURL = 'https://blog.ericthalakottur.com'
languageCode = 'en-IN'
title = "Eric Thalakottur's Blog"
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true
      [markup.goldmark.renderHooks.link]
        enableDefault = true
